"""
Project Euler Problem 2: https://projecteuler.net/problem=2

Even Fibonacci Numbers

Each new term in the Fibonacci sequence is generated by adding the previous
two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed
four million, find the sum of the even-valued terms.

References:
    - https://en.wikipedia.org/wiki/Fibonacci_number
"""

class EvenFibonacciNumbers:

    def __init__(self, n: int = 4000000):
        self.n = n

    def solution_one(self) -> int:
        """
        Returns the sum of all even fibonacci sequence elements that are lower or equal to n.
        """

        i = 1
        j = 2
        total = 0
        while j <= self.n:
            if j % 2 == 0:
                total += j
            i, j = j, i + j

        return total

    def solution_two(self) -> int:
        """
        Solution using a list to store even fibonacci sequence elements that are lower or equal to n.
        """

        even_fibs = []
        a, b = 0, 1
        while b <= self.n:
            if b % 2 == 0:
                even_fibs.append(b)
            a, b = b, a + b
        return sum(even_fibs)

    def solution_three(self) -> int:
        if self.n <= 1:
                return 0
        a = 0
        b = 2
        count = 0
        while 4 * b + a <= self.n:
            a, b = b, 4 * b + a
            count += a
        return count + b
